# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

Account:
  fields:
    list: login, name, email
    form: login, name, email, crypted_password, salt, remember_token, remember_token_expires_at, activation_code, activated_at
    show: login, name, email, crypted_password, salt, remember_token, remember_token_expires_at, activation_code, activated_at
  order_by: 
  relationships: 
  filters: 
  search: name
  application: tenavisa

Educatee:
  fields:
    list: 
    form: 
  order_by: 
  relationships: account, profile
  filters: 
  search: 
  application: tenavisa

Educator:
  fields:
    list: 
    form: 
  order_by: 
  relationships: account, profile
  filters: 
  search: 
  application: tenavisa

Operator:
  fields:
    list: 
    form: 
  order_by: 
  relationships: account, profile
  filters: 
  search: 
  application: tenavisa



Element:
  fields:
    list: position, page, key, title_cn, title_jp, kind, enabled
    form: key, page, title_cn, title_jp, kind, description, params, enabled, validation_script, prawn_output_script
    show: key, page, title_cn, title_jp, kind, description, params, enabled, validation_script, prawn_output_script
    options:
        selectors: kind
  order_by: position
  relationships: page
  filters: 
  search: 
  application: tenavisa

Page:
  fields:
    list: title
    form: title
    show: title
  order_by: 
  relationships: elements
  filters: 
  search: 
  application: tenavisa    

Profile:
  fields:
    list: educatee_id
    form: educatee_id, status
  order_by: 
  relationships: valeurs
  filters: 
  search: 
  application: tenavisa

Valeur:
  fields:
    list: element_key, profile, element
    form: element_key, valeur, profile, element
  order_by: 
  relationships: element, profile
  filters: 
  search: 
  application: tenavisa

SystemConfig:
  fields:
    list: profile_pdf_template_file_name
    form: profile_pdf_template_file_name
  order_by:
  application: tenavisa

